# Generated by Django 5.0.1 on 2024-05-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_audio_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='artists.song'),
        ),
    ]
