# Generated by Django 5.0.1 on 2024-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_audio_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.FileField(blank=None, default=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audio_uploads'),
        ),
    ]
