# Generated by Django 5.0.1 on 2024-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_video_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_album',
            field=models.FileField(blank=None, default=True, null=True, upload_to='image_album', verbose_name='Облога альбома'),
        ),
        migrations.AddField(
            model_name='song',
            name='image_song',
            field=models.FileField(blank=None, default=True, null=True, upload_to='image_song', verbose_name='Облога пісні'),
        ),
    ]
